version: '3.5'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
networks:
  default:
    name: localnet
