{
 "title": "Uniswaptest",
 "time": { "from": "2022-06-10T14:13:50.034Z", "to": "2022-09-20T03:32:43.435Z" },
 "panels": [
  {
   "title": "DAI/USDC (0.01%) Token Amounts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_amount AS \"DAI\",\n  token1_amount AS \"USDC\"\nFROM univ3.vw_history_token_amount_difference\nWHERE\n  pool_id = '0x5777d92f208679db4b9778590fa3cab3ac9e2168'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.01%) Token Amounts Diff",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_larger_diff AS \"DAI Leading Diff\",\n  token1_larger_diff AS \"USDC Leading Diff\"\nFROM univ3.vw_history_token_amount_difference\nWHERE\n  pool_id = '0x5777d92f208679db4b9778590fa3cab3ac9e2168'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.01%) Token Prices (Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_price AS \"DAI\",\n  token1_price AS \"USDC\"\nFROM univ3.vw_history_prices_by_tick_range_all\nWHERE\n  pool_id = '0x5777d92f208679db4b9778590fa3cab3ac9e2168'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.01%) Tick Prices (Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_tick_price AS \"DAI Tick Price\",\n  token1_tick_price AS \"USDC Tick Price\"\nFROM univ3.vw_history_prices_by_tick_range_all\nWHERE\n  pool_id = '0x5777d92f208679db4b9778590fa3cab3ac9e2168'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.05%) Token Amounts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_amount AS \"DAI\",\n  token1_amount AS \"USDC\"\nFROM univ3.vw_history_token_amount_difference\nWHERE\n  pool_id = '0x6c6bc977e13df9b0de53b251522280bb72383700'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.05%) Token Amounts Diff",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_larger_diff AS \"DAI Leading Diff\",\n  token1_larger_diff AS \"USDC Leading Diff\"\nFROM univ3.vw_history_token_amount_difference\nWHERE\n  pool_id = '0x6c6bc977e13df9b0de53b251522280bb72383700'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.05%) Token Prices (Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_price AS \"DAI\",\n  token1_price AS \"USDC\"\nFROM univ3.vw_history_prices_by_tick_range_all\nWHERE\n  pool_id = '0x6c6bc977e13df9b0de53b251522280bb72383700'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAI/USDC (0.05%) Tick Prices (Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_tick_price AS \"DAI Tick Price\",\n  token1_tick_price AS \"USDC Tick Price\"\nFROM univ3.vw_history_prices_by_tick_range_all\nWHERE\n  pool_id = '0x6c6bc977e13df9b0de53b251522280bb72383700'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "USDC/WETH (0.30%) Token Amounts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_amount AS \"USDC\",\n  token1_amount AS \"WETH\"\nFROM univ3.vw_history_token_amount_difference\nWHERE\n  pool_id = '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "USDC/WETH (0.30%)Token Amounts Diff",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_larger_diff AS \"USDC Leading Diff\",\n  token1_larger_diff AS \"WETH Leading Diff\"\nFROM univ3.vw_history_token_amount_difference\nWHERE\n  pool_id = '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "USDC/WETH (0.3%) Token Prices (Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_price AS \"USDC\",\n  token1_price AS \"WETH\"\nFROM univ3.vw_history_prices_by_tick_range_all\nWHERE\n  pool_id = '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "USDC/WETH (0.3%) Tick Prices (Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist_date AS \"time\",\n  token0_tick_price AS \"USDC Tick Price\",\n  token1_tick_price AS \"WETH Tick Price\"\nFROM univ3.vw_history_prices_by_tick_range_all\nWHERE\n  pool_id = '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'\nORDER BY 1"
    }
   ]
  }
 ]
}