version: '3.5'
services:
  postgres:
    container_name: pg
    image: postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db:
networks:
  default:
    name: localnet
