query HistoryQueryPoolDay {
  poolDayDatas(
    first: 3
    orderBy: date
    orderDirection: asc
    where: {
      pool: "0x5777d92f208679db4b9778590fa3cab3ac9e2168" # DAI/USDC - fee tier 100
      date_gt: 1655164800 # Jun 14, 2022 onwards (~3 months behind)
    }
  ) {
    id
    date
    tick
    volumeToken0
    volumeToken1
    token0Price
    token1Price
    volumeUSD
    tvlUSD
    txCount
    sqrtPrice
    liquidity
    feesUSD
  }
}

# curl 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://www.graphqlbin.com' --data-binary '{"query":"{\n  poolDayDatas(\n    orderBy: date\n    orderDirection: asc\n    where: {\n      pool: \"0x5777d92f208679db4b9778590fa3cab3ac9e2168\", # DAI/USDC - fee tier 100\n      date_gt: 1655164800, # Jun 14, 2022 onwards (~3 months behind)\n    }\n  ) {\n    id\n    date\n    tick\n    volumeToken0\n    volumeToken1\n    token0Price\n    token1Price\n    volumeUSD\n    tvlUSD\n    txCount\n    sqrtPrice\n    liquidity\n    feesUSD\n  }\n}"}' --compressed
